### ISSUE TITLE
Request to support compiling and installing OpenFunction (CLI) on ARM64 

### ISSUE THREAD

**Issue by FeynmanZhou** [OpenFunction/OpenFunction#200]
**Description**
A clear and concise description of what the feature is.

Support compiling and installing OpenFunction (CLI) on ARM64 

**Additional context**

@lucj compiled for darwin arm64 from the source and got the following error when Luc tried to install the framework and all its dependencies on Mac M1.

```
./ofn_darwin_arm64 install --all
Start installing OpenFunction and its dependencies.
The following components will be installed:
+------------------+---------+
| COMPONENT        | VERSION |
+------------------+---------+
| Tekton Pipelines | 0.30.0  |
| Shipwright       | 0.6.1   |
| Kourier          | 1.0.1   |
| CertManager      | 1.5.4   |
| OpenFunction     | 0.5.0   |
| Keda             | 2.4.0   |
| IngressNginx     | 1.1.0   |
| Dapr             | 1.5.1   |
| Knative Serving  | 1.0.1   |
| DefaultDomain    | 1.0.1   |
+------------------+---------+
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x101424b58]

goroutine 1 [running]:
github.com/OpenFunction/cli/pkg/components/common.(*Operator).GetInventoryRecord(0x140003509b0, {0x1019e7828, 0x14000331740}, 0x0)
	/Users/luc/Desktop/cli-0.5.2/pkg/components/common/common.go:83 +0x28
github.com/OpenFunction/cli/pkg/cmd/subcommand.(*Install).RunInstall(0x14000495f80, 0x140004ac2c0, 0x140004a6a00)
	/Users/luc/Desktop/cli-0.5.2/pkg/cmd/subcommand/install.go:247 +0x3bc
github.com/OpenFunction/cli/pkg/cmd/subcommand.NewCmdInstall.func2(0x140004a6a00, {0x14000489460, 0x0, 0x1})
	/Users/luc/Desktop/cli-0.5.2/pkg/cmd/subcommand/install.go:99 +0x88
github.com/spf13/cobra.(*Command).execute(0x140004a6a00, {0x14000489450, 0x1, 0x1})
	/Users/luc/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x14000467400)
	/Users/luc/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/luc/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
main.main()
	/Users/luc/Desktop/cli-0.5.2/cmd/main.go:9 +0x7c
```

We open this issue to track if others have the same user requests on the compiling and installing OpenFunction (CLI) on ARM64.

**Comment by trust-freedom** [comment]
keep following this issue
