### ISSUE TITLE
Using EventBus to build EventSource according to the official documentation causes openfunction-controller-manager to exit with an exception.

### ISSUE THREAD

**Issue by g-chang** [OpenFunction/OpenFunction#267]
**Description**
https://openfunction.dev/docs/user-guide/use-events/use-event-bus-and-trigger/#create-an-eventbus-and-an-eventsource
Using EventBus to build EventSource according to the official documentation causes openfunction-controller-manager to exit with an exception.

**Environmental**
+------------------+---------+
| COMPONENT        | VERSION |
+------------------+---------+
| OpenFunction     | 0.6.0   |
| Knative Serving  | 1.0.1   |
| Tekton Pipelines | 0.30.0  |
| Shipwright       | 0.6.1   |
| Dapr             | 1.5.1   |
| Keda             | 2.4.0   |
| Kourier          | 1.0.1   |
| CertManager      | 1.5.4   |
| DefaultDomain    | 1.0.1   |
+------------------+---------+

**Expected behavior**
Tell us what should happen.

**Actual behavior**
2022-04-13T02:32:10.621Z	INFO	controllers.EventSource	Updated status on EventSource	{"EventSource": "default/bus-source", "resource version": "31578422"}

 panic: runtime error: invalid memory address or nil pointer dereference

 [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16c20fe]

 

 goroutine 1086 [running]:

 github.com/openfunction/controllers/events.(*EventSourceReconciler).createOrUpdateEventSource(0xc000a69f40, 0x1c64718, 0xc0010e8270, 0x1c6e260, 0xc0008aa8d0, 0xc000376300, 0x0, 0x0)

 	/workspace/controllers/events/eventsource_controller.go:167 +0x33e

 github.com/openfunction/controllers/events.(*EventSourceReconciler).Reconcile(0xc000a69f40, 0x1c64718, 0xc0010e8270, 0xc0009dbf50, 0xb, 0xc0009dbf30, 0xa, 0xc0010e8270, 0xc000030000, 0x18d71a0, ...)

 	/workspace/controllers/events/eventsource_controller.go:100 +0x3d6

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002b4140, 0x1c64670, 0xc000738000, 0x1892f20, 0xc00077a100)

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:298 +0x30d

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002b4140, 0x1c64670, 0xc000738000, 0xc000052600)

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:253 +0x205

 sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc000724030, 0xc0002b4140, 0x1c64670, 0xc000738000)

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:214 +0x6b

 created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2

 	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.7/pkg/internal/controller/controller.go:210 +0x425

**To Reproduce**
---
apiVersion: events.openfunction.io/v1alpha1
kind: EventBus
metadata:
  name: bus-event
spec:
  natsStreaming:
    natsURL: "nats://nats.default.svc:4222"
    natsStreamingClusterID: "stan"
    subscriptionType: "queue"
    durableSubscriptionName: "ImDurable"
---
apiVersion: events.openfunction.io/v1alpha1
kind: EventSource
metadata:
  name: bus-source
spec:
  logLevel: "2"
  eventBus: "bus-event"
  kafka:
    sample-one:
      brokers: "kafka-cluster-kafka-bootstrap.infrastructure:9092"
      topic: "kafka-input-toptic"
      authRequired: false 

**Screenshots**

**Additional context**
View by the number of lines of code at the time of the exception，https://github.com/OpenFunction/OpenFunction/blob/78decdf70a3c9839b73a2eda0fee1132e36a7759/controllers/events/eventsource_controller.go#L167  
	newSinkUri := *eventSource.Spec.Sink.Uri

**Comment by tpiperatgod** [comment]
The original processing logic here is as follows:

`spec.sink` supports data in the form of `uri` and `ref`, where `uri` is the accessible HTTP address and `ref` represents a reference to a Knative Service or OpenFunction Function resource to get the HTTP access address of those resources.

Regardless of which method is used, we have to update the HTTP address generated to the `spec.sink.uri` at the end, representing the final result.

So a prerequisite needs to be added to the code you pointed out, and that is to determine if `spec.sink` has been set.

I think this fits as a "good-first-issue" so if you're interested in fixing it, please let me know. 😀

**Comment by Aarush-Goyal** [comment]
@tpiperatgod I would like to try and fix it

**Comment by tpiperatgod** [comment]
> @tpiperatgod I would like to try and fix it

Great! Please let me know if you need any other information.

**Comment by KlausMikhaelson** [comment]
Hey @tpiperatgod is this issue still open ? if yes than can I work on it ?
