### ISSUE TITLE
OpenFunction Controller Crashing with Envoy Service Annotations

### ISSUE THREAD

**Issue by Mershab99** [OpenFunction/OpenFunction#525]
**Description**
The OpenFunction controller does not accept the Envoy LoadBalancer service having any annotations attached to it beforehand.

**Environmental**
Tell us what your cluster environment is like, e.g.

K3s (vcluster) v1.27.3
OpenFunction Helm chart version 0.7.0
Default dependent component versions from chart

**Expected behavior**
The injected annotations are appended to the existing annotations on the gateway and controller does not crash.

**Actual behavior**
Controller crashes trying to reconcile the K8sGateway (see `Additional Context` below for detailed log

**To Reproduce**

1. Install OpenFunction with values file addition as below:
`        contour:
          envoy:
            service:
              annotations:
                foo: bar

`
2. See error

**Screenshots**
(Screenshot showing the same stacktrace as below)
<img width="1456" alt="Screenshot 2024-06-19 at 01 16 30" src="https://github.com/OpenFunction/OpenFunction/assets/9834945/91131dbc-15d6-428c-a220-2e15b9d10c12">

**Additional context**

```W0619 06:10:50.919931       1 warnings.go:70] The v1alpha2 version of Gateway has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "builder", "controllerGroup": "core.openfunction.io", "controllerKind": "Builder", "worker count": 1}
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "trigger", "controllerGroup": "events.openfunction.io", "controllerKind": "Trigger", "worker count": 1}
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "gateway", "controllerGroup": "networking.openfunction.io", "controllerKind": "Gateway", "worker count": 1}
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "eventsource", "controllerGroup": "events.openfunction.io", "controllerKind": "EventSource", "worker count": 1}
2024-06-19T06:10:50Z	ERROR	controllers.Gateway.cleanK8sGatewayResources	Failed to Unmarshal GatewayConfigAnnotation	{"error": "unexpected end of JSON input"}
2024-06-19T06:10:50Z	ERROR	controllers.Gateway.reconcileK8sGateway	Failed to Unmarshal GatewayConfigAnnotation	{"error": "unexpected end of JSON input"}
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "function", "controllerGroup": "core.openfunction.io", "controllerKind": "Function", "worker count": 1}
2024-06-19T06:10:50Z	INFO	Starting workers	{"controller": "serving", "controllerGroup": "core.openfunction.io", "controllerKind": "Serving", "worker count": 1}
2024-06-19T06:10:50Z	INFO	KubeAPIWarningLogger	The v1alpha2 version of Gateway has been deprecated and will be removed in a future release of the API. Please upgrade to v1beta1.
2024-06-19T06:10:50Z	INFO	controllers.Gateway.reconcileK8sGateway	K8s Gateway Reconciled	{"namespace": "projectcontour", "name": "contour"}
2024-06-19T06:10:50Z	INFO	controllers.Gateway.updateGatewayStatus	Updated status on Gateway	{"namespace": "openfunction", "name": "openfunction"}
2024-06-19T06:10:50Z	ERROR	controllers.Gateway.updateGatewayAnnotations	Failed to Unmarshal GatewayConfigAnnotation	{"error": "unexpected end of JSON input"}
2024-06-19T06:10:50Z	INFO	Observed a panic in reconciler: assignment to entry in nil map	{"controller": "gateway", "controllerGroup": "networking.openfunction.io", "controllerKind": "Gateway", "Gateway": {"name":"openfunction","namespace":"openfunction"}, "namespace": "openfunction", "name": "openfunction", "reconcileID": "15e14df5-e2b9-4f59-ab1c-86e64610a9b2"}
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
goroutine 605 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x1783be0, 0x1c13650})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/openfunction/controllers/networking.(*GatewayReconciler).updateGatewayAnnotations(0xc0001145a0, 0xc000a44000)
	/workspace/controllers/networking/gateway_controller.go:384 +0x2dc
github.com/openfunction/controllers/networking.(*GatewayReconciler).Reconcile(0xc0001145a0, {0x1c2df38?, 0xc0007bd1d0}, {{{0xc00038f300, 0xc}, {0xc00038f2f0, 0xc}}})
	/workspace/controllers/networking/gateway_controller.go:125 +0x5c5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1c2df38?, {0x1c2df38?, 0xc0007bd1d0?}, {{{0xc00038f300?, 0x1703e80?}, {0xc00038f2f0?, 0x10?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0003125a0, {0x1c2de90, 0xc00067e6c0}, {0x17e5300?, 0xc001012000?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003125a0, {0x1c2de90, 0xc00067e6c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:231 +0x333```

**Comment by tpiperatgod** [comment]
I can't find the `contour.envoy.service` configuration in the values file of the chart, can you provide a more complete configuration? Or can you provide more detailed steps to reproduce it?

**Comment by benjaminhuo** [comment]
cc @wrongerror

**Comment by Mershab99** [comment]
> I can't find the `contour.envoy.service` configuration in the values file of the chart, can you provide a more complete configuration? Or can you provide more detailed steps to reproduce it?

Apologies for the late response. 

It isn't directly in the values file, but adding a value to `contour.envoy.service` will edit the underlying contour helm chart. [Referenced here.](https://artifacthub.io/packages/helm/bitnami/contour)

My full values file is as follows:
```
global:
  Contour:
    enabled: false
  KnativeServing:
    enabled: false
contour:
  envoy:
    service:
      annotations:
        chisel-operator.io/exit-node-provisioner: chisel-operator-system/digitalocean

```

I am using an operator called the [chisel operator](https://chisel.fyralabs.com/guides/installation/). (I've linked the installation guide as reference). This operator creates an SSH tunnel to an on the fly provisioned VPS. Essentially allowing for a public loadbalancer IP. 

Regardless, this crashes the OF controller due to the error mentioned above. However I don't believe it is solely due to this operator, I think it is a general error that occurs when other labels are added to the Gateway object that the OF Controller manages.
